### ISSUE TITLE
Build Error on clean Ubuntu server

### ISSUE THREAD

**Issue by DeserranoJorden** [NeuraLegion/brokencrystals#250]
Installed node v14 on a fresh Ubuntu server and tried installing this application.

```
root@server:/home/ubuntu/brokencrystals# node -v
v14.21.3
root@server:/home/ubuntu/brokencrystals# npm -v
6.14.18
```

But I keep getting errors and I have no direct clue how to solve them:

```
root@server:/home/ubuntu/brokencrystals# sudo npm ci && sudo npm run build
npm WARN prepare removing existing node_modules/ before installation

> libxmljs2@0.31.0 install /home/ubuntu/brokencrystals/node_modules/libxmljs2
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp http GET https://github.com/marudor/libxmljs2/releases/download/v0.31.0/node-v83-linux-x64-glibc.tar.gz
[libxmljs2] Success: "/home/ubuntu/brokencrystals/node_modules/libxmljs2/build/Release/xmljs.node" is installed via remote

> libxmljs@0.19.7 install /home/ubuntu/brokencrystals/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v83-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v83-linux-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v83-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for libxmljs@0.19.7 and node@14.21.3 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v83-linux-x64.tar.gz
make: Entering directory '/home/ubuntu/brokencrystals/node_modules/libxmljs/build'
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
make: g++: No such file or directory
make: *** [xmljs.target.mk:165: Release/obj.target/xmljs/src/libxmljs.o] Error 127
make: Leaving directory '/home/ubuntu/brokencrystals/node_modules/libxmljs/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Linux 5.15.0-60-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/home/ubuntu/brokencrystals/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/home/ubuntu/brokencrystals/node_modules/libxmljs/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/ubuntu/brokencrystals/node_modules/libxmljs
gyp ERR! node -v v14.21.3
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/ubuntu/brokencrystals/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/ubuntu/brokencrystals/node_modules/libxmljs/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ubuntu/brokencrystals/node_modules/libxmljs/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1088:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
node-pre-gyp ERR! System Linux 5.15.0-60-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/ubuntu/brokencrystals/node_modules/libxmljs/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /home/ubuntu/brokencrystals/node_modules/libxmljs
node-pre-gyp ERR! node -v v14.21.3
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/ubuntu/brokencrystals/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/ubuntu/brokencrystals/node_modules/libxmljs/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs@0.19.7 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.19.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-01T10_48_11_271Z-debug.log
```

**Comment by DeserranoJorden** [comment]
For people having the same issue:

I was missing some packages like gcc, make and g++ on my Ubuntu.
